### ISSUE TITLE
[Readme] Clarification please, what are the hardware/software requirements?

### ISSUE THREAD

**Issue by owlboy** [Fewes/BNAO#3]
Hello!

This looks super nifty, and I am interested in seeing if it works for my project.

Just a nitpick about the readme, I see in the description this is GPU accelerated. I have found recently this usually means Nvidia + WIndows only. Could you please clairfy the system/software requirements to run this?

Unity versions, if specific hardware is needed, if Windows is needed.

Thanks!

**Comment by Fewes** [comment]
Good call! It should run on just about any GPU as long as it supports floating point + shadow map render textures.  I'll add a "Requirements" section to the readme. I'm not sure about platform limitations, but I don't see why it would be limited to Windows. If anyone can test this I'll gladly add the info. Thanks!

**Comment by Fewes** [comment]
Added the mentioned info in 8db78aa165f0038903376d4e2da6fbb6395d912f
